### ISSUE TITLE
[DOC] - Add documentation for Gitpod

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#126]
## Summary

Now that we have Gitpod working in jupyter/accessibility we need to document how this works and how folks might use it

**Comment by isabela-pf** [comment]
I don't have the knowledge to lead this so I haven't assigned it to myself. But if anyone wants my help
- Reviewing their work (as someone not very familiar with gitpod)
- Adding support material like graphics or flow chart

I'm happy to step in.
