### ISSUE TITLE
Imagine test reporting options

### ISSUE THREAD

**Issue by isabela-pf** [Quansight-Labs/jupyter-a11y-mgmt#131]
## Summary
Based on sprint planning discussions in #114. Also a step in the larger goal #1. 

This is a high-level exploration of test reporting options so that we can narrow down into other concrete actions in the future. Quoting from #114

> Start thinking about how we want to report test results to the community, which I think could be a lot of things and depends more on what we decide. For example
> -   How do we communicate that these tests are not the end-all-be-all for accessibility?
> -   Where do these reports live in relation to the main projects? What info do they include?
> -   What would a website with a list of reports include? What ways would we want people to interact with it?
> -   Is there a way to tie this into some kind of social media updates for accountability?

## Acceptance Criteria

We have recorded versions of this exploration with some takeaways flagged for follow up. 

## Tasks to complete

This is open to suggestion. I think it may include.
- Follow up on existing user stories
- Add more reporting-specific user stories
- Brainstorm the magical, ideal-world, perfect reports we'd like to read (sketches, references, feature list, those kind of things)
- Record all this
- Take note of elements we want to turn into future tasks (probably on this issue)

**Comment by trallard** [comment]
@trallard  to add details next week

**Comment by trallard** [comment]
Inspo: https://www.astropy.org/astropy-benchmarks/
