### ISSUE TITLE
[TEST] - Add automated accessibility tests to Jupyterlab's documentation theme

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#14]
## Background

We want to ensure that both the codebase and documentation are accessible 

## Steps to complete this goal

- We propose using pa11y and lighthouse

**Comment by isabela-pf** [comment]
Based on our discussion, I also wanted to link to some related docs testing work at
- [pydata/pydata-sphinx-theme #294 Add pa11y testing and reporting](https://github.com/pydata/pydata-sphinx-theme/pull/294)
- [comment on executablebooks/meta #279 Discuss shared theme infrastructure between EBP and other themes](https://github.com/executablebooks/meta/issues/279#issuecomment-796857280)
