### ISSUE TITLE
Rendered notebook UX fixes - Round 1

### ISSUE THREAD

**Issue by isabela-pf** [Quansight-Labs/jupyter-a11y-mgmt#148]
## Summary

This is a part of the [STScI collaborative rendered notebook research](https://github.com/Iota-School/notebooks-for-all). We're working together to run accessibility-focused user testing on static forms of notebooks. The aim is to provide open research for the betterment of the community and to learn more about accessibility needs in all notebooks by starting with their static versions. I've been asked to open issues for these tasks in this repo for easier tracking.

This issue is a placeholder for the fixes we anticipate working on as a response to findings in #146. We do not yet know what these fixes be, so this issue will be updated post-round 1 user testing. Goals for this section include

- Removing blocking/critical barriers that prevented task completion in user testing round 1.
- Improving any bugs or missed accessibility opportunities that were encountered in user testing round 1.
- Realizing and exploring improvement of areas preferred by test participants in user testing round 1.
- Documenting changes made via change log.

## Acceptance Criteria

This issue may be closed when all user testing information for this round is stored in the [project repo](https://github.com/Iota-School/notebooks-for-all) and recorded/linked in this issue.

(If you can think of something else, let me know!)

## Tasks to complete

To be determined via linked issues. This must be decided post #146.

**Comment by trallard** [comment]
This is complete right @isabela-pf? if so lmk and I can close the issue
