### ISSUE TITLE
DOC - Report Zoom audit findings on JupyterLab

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#153]
## Summary

@steff456  has carried out a rather thorough audit on JupyterLab zoom 
And a corresponding summary: https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/152

## Tasks to complete

These needs to be added to the jupyter/accessibility repo under an Audit section

**Comment by steff456** [comment]
Once PR https://github.com/jupyter/accessibility/pull/111 is merged this issue can be closed
