### ISSUE TITLE
Develop pathways for participatory community engagement

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#3]
## Background

The whole goal of this grant is to make Jupyter and Scientific computing more equitable and accessible to all. We can only consider it a success if we engage with the disabled community, thus we want to develop solid processes to engage with the community and onboard them to the ecosystem. 

## Expected timeline

- The whole duration of the grant (24 months)
- First deliverable within 6 months

## Steps to complete this goal

Related to #2

**Comment by trallard** [comment]
We have had some discussions on how we can do this and align with other projects' efforts.

Let's work towards documenting and consolidating these ideas.

**Comment by isabela-pf** [comment]
I started brainstorming some [ideas for other contribution events on this issue](https://github.com/isabela-pf/a11y-events/issues/4). Feel free to add to this list if you have ideas.

At some point I plan to weigh these ideas and figure out which ones to move forward with in the context of this grant.

**Comment by isabela-pf** [comment]
I just added rough agendas (for further critique of contribution event ideas) to the same issue I've been working on. [Start of agenda comments](https://github.com/isabela-pf/a11y-events/issues/4#issuecomment-1124536984). 

Feel free to give feedback or new ideas!

**Comment by trallard** [comment]
Moved over to discussions to make it easier to navigate and have unstructured convos 🔈  love all the ideas
