### ISSUE TITLE
Outreach activities - planning 

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#32]
## Background

Define outreach activities to support the grant and its outcomes (conferences, write-ups, social media, community calls, anything)

## Expected timeline

6 months - this will be a rolling issue over the grant

💡  Add your ideas as comments

**Comment by isabela-pf** [comment]
I have a question since I'm not familiar conferences. 

Would the idea for these to be to gain awareness of the project by speaking on efforts that have been done and what's next at a conference? Or is there some other way conference's might support us that I'm not aware of?
