### ISSUE TITLE
Decide on the best format for the roadmap 

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#34]

**Comment by trallard** [comment]
Adding links to some roadmaps for inspiration:

- [GitKraken roadmap](https://www.gitkraken.com/git-client/roadmap)
- [VSCode](https://github.com/microsoft/vscode-wiki/blob/main/Roadmap.md)
- [Jupyter roadmap repo](https://github.com/jupyter/roadmap)
- [JupyertHub roadmap](https://github.com/jupyterhub/jupyterhub/blob/main/docs/source/contributing/roadmap.md)
- [Rust roadmap blogpost](https://blog.rust-lang.org/2020/09/03/Planning-2021-Roadmap.html)

📚  Other

- [Managing an oss product roadmap](https://opensource.com/article/21/9/open-source-product-roadmap) - article

**Comment by gabalafou** [comment]
Couple quick thoughts:

- Dates. First published, last updated. I like to see those on public docs
- Section on edit frequency. How frequently will we update the roadmap, is it subject to change? If so, when will those change points likely occur?

**Comment by trallard** [comment]
I think of a roadmap as a dynamic document, I think we should revisit it at least every 6 months as we have those as marked milestones for the project itself.

Also I am +1 on adding dates

**Comment by trallard** [comment]
📜  Hackmd messy brain land: https://hackmd.io/YgBYcgYxRieJnVMWsk1QqA?both

**Comment by trallard** [comment]
- [ ] @tonyfast @gabalafou  review: https://hackmd.io/Asvlu_rsTtu8eCxGB5V8nA?both and add comments
- [ ] @isabela-pf  once reviewed: open a PR against the repo to add to our compass

**Comment by trallard** [comment]
Update: we have also decided to add the roadmap to https://github.com/jupyter/accessibility to ensure this lives in a "neutral" area
