### ISSUE TITLE
Update JLab contributing guidelines as needed 

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#37]
## Summary

Jlab contribution guidelines can be found at <https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html>
and the instructions for local env set up at <https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#setting-up-a-local-development-environment>

As we onboard @gabalafou  and others we should ensure we contribute patches or updates as needed

**Comment by gabalafou** [comment]
Pasting some notes from my notebook when I was setting up my environment.

---

Thoughts getting JupyterLab running locally from docs:
- Single source of truth for contributor docs: good! https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html
- In the above doc, lots of links but no quick "getting started" section. Not sure where to begin, or what sequence of steps to take. "Installing Node.js and jlpm" section does not cover how to install jlpm; it only covers Node.js.
- would be great if readthedocs automatically published a “last updated” datetime string on doc pages

**Comment by trallard** [comment]
@gabalafou do you think we should send a PR to tackle some of these ☝🏽 ? else we can close this issue and send PR's as needed with other deliverables/items?

**Comment by trallard** [comment]
Just going to mark it as on hold and move over to the next milestone

**Comment by trallard** [comment]
Other items that will need documenting:

- CI use (once the doit items are merged and we got a CI)
- scope of what is being tested vs not
- how to local/Gitpod development work
