### ISSUE TITLE
Add CoC to this repo

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#40]
## Summary

We must add a CoC

## Acceptance Criteria

A CoC is available in the repo and team-compass (see #38 )

The question is: what CoC should we adopt, do we want to use the Jupyter one with some amendments (i.e. adding explicit wanted and unwanted behaviour) or other, please add ideas here @tonyfast @isabela-pf

**Comment by isabela-pf** [comment]
I think the we are a part of the Jupyter community and should probably at the very least use the Jupyter Code of Conduct as a foundation. Personally, I think that code of conduct is missing some specificity that makes it more enforceable, so I'd be open to the kinds of additions that explicitly call out unwanted behavior.

My proposal would be to  follow the pattern of the amendments we added to the [tentative accessibility workshop code of conduct](https://github.com/Quansight-Labs/jupyter-accessibility-workshops/blob/05afb632df575b00de3442ff6849e24c9b35c0fb/code-of-conduct.md) and modify them to not be as synchronous-event specific. We don't want to undermine the main Jupyter CoC that we definitely all are responsible to adhere to, so maybe adding something like `our team feels the need to specify unacceptable behavior is as follows`.

**Comment by trallard** [comment]
Agree - since you already have worked on this in the past, I will assign you this issue and I can do the review @isabela-pf
