### ISSUE TITLE
Decide on framework (proposed: jest-axe and Galata)

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#51]
- [x] Need to discuss and make decisions on: 
    - [x] Where will these tests live 1) in the repo of the tool tested 2) aggregate all the tools in the a11y repo
    - [x]  Identify how adding the a11y tests will affect the user/contributor experience
    - [x] How to go about the actual a11y automated tests (see below for more details)
 
---
   
 #### Implementation steps 
- See #4  and the issues linked to 
- Run a comparative analysis of the tools
- Can we create diagrams on how the best path forward to implement the tests: architecture, onion/dependencies layers ?

**Comment by trallard** [comment]
@gabalafou  is currently working on a scoping doc for the framework

@tonyfast  will work on any technical items within https://github.com/jupyter/accessibility to ensure we can start contributing tests in there to avoid any barriers/unwanted behaviours in the exiting contributor workflows

**Comment by trallard** [comment]
> How to go about the actual a11y automated tests (see below for more details)

Related to #95

**Comment by trallard** [comment]
This seems to have been tackled mostly by the RFD #97 - WDYT @gabalafou @isabela-pf ?

**Comment by isabela-pf** [comment]
> This seems to have been tackled mostly by the RFD https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/97 - WDYT @gabalafou @isabela-pf ?

I agree. I think the choice has pretty much been made since the PR exists, and I think we can always return here for discussion if needed.
