### ISSUE TITLE
Add outputs of comparison Retro vs JupyterLab to a11y repo

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#74]
## Summary

@gabalafou  already completed a nice comparison (see #68) this should be added to https://github.com/jupyter/accessibility to make it visible to the wider community and start building our docs

## Acceptance Criteria

Merged into https://github.com/jupyter/accessibility

**Comment by gabalafou** [comment]
Started PR: https://github.com/jupyter/accessibility/pull/66

**Comment by trallard** [comment]
Merged so closing
