### ISSUE TITLE
Open PR of small edits to JupyterLab's contributing doc

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/jupyter-a11y-mgmt#80]
## Summary
There are some small edits (small edit means sentence or paragraph level edits, not section level) that could be made to improve the contributing doc, for example a quick note explaining what `jlpm` is, rather than assuming a new contributor knows what it is. 

## Acceptance Criteria
Open PR against the JupyterLab repo, get it reviewed, and then merged in

**Comment by trallard** [comment]
@gabalafou  is this still applicable or shall we archive?

**Comment by gabalafou** [comment]
It's still applicable but not priority for me today 😬 .
Now that my other checkboxes PR is up, I'll try to cross this one off this week.
