### ISSUE TITLE
Add Workshop materials to compass

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyter-a11y-mgmt#93]
Need to add the assets from the a11y workshop to the [Compass media section ](https://jupyter-a11y.netlify.app/news-media/intro.html)

**Comment by trallard** [comment]
@isabela-pf we did do this right?

**Comment by isabela-pf** [comment]
Everything is in [quansight-labs/jupyter-accessibility-workshops/events](https://github.com/Quansight-Labs/jupyter-accessibility-workshops/tree/main/events), but I have not yet opened a PR to link to these resources from anywhere else. 

I thought this needed a PR to jupyter/accessibility, but by compass do you mean the compass in this repo? Sorry for the confusion.

**Comment by trallard** [comment]
Send a PR with a link to https://github.com/Quansight-Labs/jupyter-accessibility-workshops/tree/main/events

**Comment by isabela-pf** [comment]
I have two PRs for this.
- #127 adds the links to this team compass
- [Quansight-Labs/accessibility #7](https://github.com/Quansight-Labs/accessibility/pull/7) (because I think this should also be in the jupyter/accessibility repo.

**Comment by isabela-pf** [comment]
I opened a PR at [jupyter/accessibility #94](https://github.com/jupyter/accessibility/pull/94) for this.
