### ISSUE TITLE
Create proposal for 2022 summer internship

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/jupyter-a11y-mgmt#96]
## Summary

From Slack:

[Gabriel (UTC-6)](https://app.slack.com/team/U02JA56KDDY)  [10:48 AM](https://quansight.slack.com/archives/C02HG0AHA9H/p1649778511688229)
Hey team! How do we feel about trying to bring on a summer intern? I think accessibility work is fascinating and could be foundational to the growth and development of an aspiring software developer. I also think that working on solving something like 400% zoom in JupyterLab would confer a lot of transferable knowledge and skills; albeit also a bunch of non-transferable, JupyterLab-specific skills like learning Lumino. (But even that—learning a new framework—is a transferable skill in the JavaScript ecosystem of ever-evolving fads, trends, and frameworks.) Thoughts?

[Gabriel (UTC-6)](https://app.slack.com/team/U02JA56KDDY)  [10:53 AM](https://quansight.slack.com/archives/C02HG0AHA9H/p1649778805188269)
I also think that 400% zoom is a reasonable chunk of work for a summer internship if the summer intern comes in with some foundations already laid in HTML, CSS, and JavaScript/programming. Well… some programming knowledge is absolutely mandatory for 400% zoom to be a reasonable scope of work for the summer… and if they don’t already have some familiarity with HTML/CSS/JavaScript/TypeScript, then they would need to be a very fast or very dedicated learner

[Tania Allard](https://app.slack.com/team/U01EQ7H2N9H)  [10:54 AM](https://quansight.slack.com/archives/C02HG0AHA9H/p1649778868353889)
We can definitely plan for a summer intern(s) - :me-too:  from me on the proposed focus - we can always start with a very slim goal and build /adjust as we see how the intern is doing (edited) 

[Gabriel (UTC-6)](https://app.slack.com/team/U02JA56KDDY)  [10:58 AM](https://quansight.slack.com/archives/C02HG0AHA9H/p1649779094835829)
Awesome! I’ll write something up this week

[Tania Allard](https://app.slack.com/team/U01EQ7H2N9H)  [11:01 AM](https://quansight.slack.com/archives/C02HG0AHA9H/p1649779260239499)
Thank you :pray::skin-tone-4:  it does not have to be super thorough  - also could you add this as an issue on the repo? just so we can keep track of items?

## Acceptance Criteria
- [ ] Issue created on https://github.com/Quansight-Labs/internship-2022

## Tasks to complete
- [ ] Create issue at https://github.com/Quansight-Labs/internship-2022

## Past proposals

From Isabela:

I have a template from past intern proposals if that would help!
[2021 one](https://github.com/Quansight-Labs/internship-2021/blob/main/proposals/ethics-focused-numpy-tutorial.md)
[2022 one](https://github.com/isabela-pf/internship/blob/main/accessible-collaborative-editing-research.md)

**Comment by gabalafou** [comment]
[Note from Isabela on Slack:](https://quansight.slack.com/archives/C02HG0AHA9H/p1649781759808419?thread_ts=1649778805.188269&cid=C02HG0AHA9H)
I agree this is scopeable and is probably one of the less controversial Jupyter accessibility PRs, so it may get along better with the community. Good idea!

**Comment by isabela-pf** [comment]
I think the acceptance criteria could actually be to create an issue on the [2022 internship repo](https://github.com/Quansight-Labs/internship-2022). I think projects only get added to the projects directory if they end up having an intern to pair them with, which is not directly in your control. 

Also copied over from my slack follow-up:
> Oops, I found a [new template in the 2022 repo](https://github.com/Quansight-Labs/internship-2022/blob/main/projects/project_template.md). It's probably good to work with that then. Although I like some of [the additions added in this issue for ideas](https://github.com/Quansight-Labs/internship-2022/issues/2). (like the roadmap)

**Comment by gabalafou** [comment]
Closing this issue because I submitted the internship proposal to the [Quansight-Labs/internship-2022](https://github.com/Quansight-Labs/internship-2022) repo
